### ISSUE TITLE
You commited the vite.config caching thing

### ISSUE THREAD

**Issue by mybearworld** [WlodekM/meower-barebones-v2#1]
https://github.com/WlodekM/meower-barebones-v2/blob/main/vite.config.js.timestamp-1705390512650-cb0b5196eb8a9.mjs

**Comment by WlodekM** [comment]
I don't remember commenting that out, but it still works fine, right?

**Comment by mybearworld** [comment]
It still works fine, but it's a file that Vite creates to promptly delete it, it's not really supposed to be commited

**Comment by WlodekM** [comment]
I think MD already removed the cache, but i won't remove the whole file because i need it for building

**Comment by mybearworld** [comment]
The vite.config.js file being there is good, just the timestamp one shouldn't be there
